trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/nGratis.Cop.Olympus.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true
  submodules: true

- task: CmdLine@2
  displayName: 'Restore .NET tools'
  inputs:
    script: 'dotnet tool restore'
    workingDirectory: 'Source'

- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: 'Source/nGratis.Cop.Olympus.sln'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **/bin/$(buildConfiguration)/**/*Test.dll
      !**/bin/**/ref/**
    searchFolder: 'Source'
    pathToCustomTestAdapters: '$(UserProfile)/.nuget/packages/xunit.runner.visualstudio/2.4.1/build/_common'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'