trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/nGratis.Cop.Olympus.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packagesDirectory: Source/packages

steps:
- checkout: self
  clean: true
  submodules: true

- task: Cache@2
  inputs: 
    key: 'paket | "$(Agent.OS)" | Source/paket.lock'
    restoreKeys: |
       paket | "$(Agent.OS)"
       paket
    path: $(packagesDirectory)
  displayName: Cache NuGet packages

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: Source/nGratis.Cop.Olympus.sln

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**/bin/$(buildConfiguration)/**/*Test.dll'
    searchFolder: 'Source'
    pathToCustomTestAdapters: 'Source/packages/_test/xunit.runner.visualstudio/build/_common'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'